# branches to build
branches:
  # whitelist
  only:
    - master

os: Visual Studio 2015

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release
  
build_script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake --build .
  - cmake --build . --config Release

test: off
test_script: off
deploy: off
