# branches to build
branches:
  # whitelist
  only:
    - master

os:
  - Visual Studio 2013
  - Visual Studio 2015

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release
  
build_script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake -DBUILD_TESTING=OFF ..
  - cmake --build .
  - cmake --build . --config Release

test: OFF
test_script: OFF
deploy: off
